name: "Linter"

on:
  push:
  pull_request:

jobs:
  dockerfile:
    name: Linter for Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: app/Dockerfile
  django-lint:
    name: Linter for Django
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.10.10
      - name: Linting
        run: bash bin/cleanup_pre_commit.sh
